version: 2
jobs:
  build:
    working_directory: ~/rap-sheet-parser

    # Primary container image where all commands run

    docker:
    - image: circleci/ruby:2.5.1

    steps:
    - checkout

    # Restore bundle cache
    - restore_cache:
        keys:
        - rap-sheet-parser-{{ checksum "Gemfile.lock" }}
        - rap-sheet-parser-

    # Bundle install dependencies
    - run:
        name: Install dependencies
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

    # Store bundle cache
    - save_cache:
        key: rap-sheet-parser-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - run: mkdir ~/rspec
    - run:
        name: Run tests
        command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
        when: always
    - store_test_results:
        path: ~/rspec

    - run:
        name: Run integration
        command: bundle exec rspec spec/integration_spec.rb --tag integration

    # Save artifacts
    - store_test_results:
        path: /tmp/test-results
